name: Build AssetsManager

"on":
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pywebview pyinstaller
      - run: pyinstaller --onefile --windowed --add-data "index.html;." --name "AssetsManager-Windows" main.py
      - uses: actions/upload-artifact@v4
        with:
          name: AssetsManager-Windows
          path: dist/AssetsManager-Windows.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pywebview pyinstaller
      - run: pyinstaller --onefile --windowed --add-data "index.html:." --name "AssetsManager-Mac" main.py
      - uses: actions/upload-artifact@v4
        with:
          name: AssetsManager-Mac
          path: dist/AssetsManager-Mac